# Menu CRUD ==========
### index
GET http://localhost:3000/menus.json

### show
GET http://localhost:3000/menus/3.json

### create
POST http://localhost:3000/menus.json
Content-Type: application/json

{
  "title": "Facial",
  "duration": "01:00:00",
  "price": 120,
  "description": "Full face"
}

### update
PATCH http://localhost:3000/menus/4.json
Content-Type: application/json

{
  "title": "Facial",
  "duration": "01:00:00",
  "price": 120,
  "description": "Full face"
}

### delete
DELETE http://localhost:3000/menus/4.json



# User CRUD ==========
### index
GET http://localhost:3000/users.json

### show
GET http://localhost:3000/users/1.json

### create
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "first_name": "Azumi",
  "last_name": "Kobayashi",
  "password": "password",
  "email": "test@test.com",
  "phone": "123-456-7890",
  "gender": "female",
  "zip": "10001",
  "state": "NY",
  "city": "New York",
  "address": "20 Hudson Yards",
  "note": "This is a note for Azumi",
  "birthday": "1981-10-07",
  "status": "admin"
}

### update
PATCH http://localhost:3000/users/4.json
Content-Type: application/json

{
  "first_name": "Test First_name",
  "last_name": "Test Last_name",
  "password": "password",
  "email": "test@test.com",
  "phone": "123-456-7890",
  "gender": "n/a",
  "zip": "10001",
  "state": "NY",
  "city": "New York",
  "address": "20 Hudson Yards",
  "note": "This is a note for Azumi",
  "birthday": "2022-04-22",
  "status": "system"
}

### destroy
DELETE http://localhost:3000/users/3.json



# Event CRUD =======
### index
GET http://localhost:3000/events.json

### show
GET http://localhost:3000/events/1.json

### create
POST http://localhost:3000/events.json
Content-Type: application/json

{
  "date": "2022-04-23",
  "start": "14:00:00",
  "end": "15:30:00",
  "user_id": 1,
  "duration_total": "1:30:00",
  "menus": [1, 2]
}

### update
PATCH http://localhost:3000/events/22.json
Content-Type: application/json

{
  "date": "2022-04-23",
  "start": "14:00:00",
  "end": "16:30:00",
  "user_id": 1,
  "duration_total": "2:30:00",
  "menus": [1, 2, 3]
}

### destroy
DELETE http://localhost:3000/events/21.json



# EventMenu CRUD ==========
### index
GET http://localhost:3000/event_menus.json

### show
GET http://localhost:3000/event_menus/1.json

### create
POST http://localhost:3000/event_menus.json
Content-Type: application/json

{
  "event_id": 1,
  "menu_id": 1,
  "user_id": 1,
  "status": "booked"
}

### update
PATCH http://localhost:3000/event_menus/1.json
Content-Type: application/json

{
  "event_id": 1,
  "menu_id": 1,
  "user_id": 1,
  "status": "booked"
}

### destroy
DELETE http://localhost:3000/event_menus/5.json



# BusinessTime CRUD
### index
GET http://localhost:3000/business_times.json

### show
GEt http://localhost:3000/business_times/1.json

### create
POST http://localhost:3000/business_times.json
Content-Type: application/json

{
  "date": "2022-04-29",
  "time": "2000-01-01T13:00:00.000Z",
  "available": false,
  "event_id": 3
}

### update
PATCH http://localhost:3000/business_times/7.json
Content-Type: application/json

{
  "date": "2022-04-30",
  "time": "2000-01-01T13:00:00.000Z",
  "available": false,
  "event_id": 3
}

### destroy
DELETE http://localhost:3000/business_times/7.json